version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ajasra-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ajasrabyittika
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      - redis
    networks:
      - ajasra-network

  # Redis service
  redis:
    image: redis:latest
    container_name: ajasra-redis
    restart: unless-stopped
    command: redis-server --requirepass ajasrabyittika
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ajasra-network

networks:
  ajasra-network:
    driver: bridge

volumes:
  redis-data: